name: test-action

on:
  pull_request: []

jobs:
  test-action:
    name: Test Build Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install CSS Clean
        run: pip install -e .[all]

      - name: Test CSS Clean
        uses: ./action/clean
        with:
          css: cssclean/tests/testdata/1/style.css
          html: cssclean/tests/testdata/1/table.html cssclean/tests/testdata/1/home.html
          
      - name: Test SCSS Clean
        uses: ./action/clean
        with:
          css: cssclean/tests/testdata/3/style.scss
          html: cssclean/tests/testdata/3/index.html
